# Book settings
title:
author: Western and Central Africa Poverty & Equity
logo: BFA_proportion_every5_casestudies.png

repository:
    url: https://github.com/gracedoherty/Geotemporal-Urbanization-in-the-Sahel
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://worldbank.github.io/template

only_build_toc_files: true
